# This is the configuration file for the plugin SimpleShopGUI.
# Do not mess with the values and keys if you don't know how to edit a YAML file!
# Do not change value types, like integer to string or list to integer... etc.

database:
  # Supported databases: sqlite, postgresql, mysql
  provider: "sqlite"

  # SQLite config
  sqlite:
    path: "database.db"

  # PostgreSQL config
  postgresql:
    host: "HOST"
    port: 2565
    database: "DATABASE_NAME"
    username: "USERNAME"
    password: "PASSWORD"

  # MySQL config
  mysql:
    host: "HOST"
    port: 2565
    database: "DATABASE_NAME"
    username: "USERNAME"
    password: "PASSWORD"

shop:
  max_items_duration: 604800000 # 1 week. The time should be in milliseconds
  show_buy_notification: true # Show notification to sellers (if they are online) when there is a player who bought one of their items (true = Enable, false = Disable)
  time_remaining_format: "%days% days, %hours% hours, %minutes% minutes, %seconds% seconds" # Time format, example: 4 days, 6 hours, 47 minutes, 22 seconds
  max_item_price: 18446744073709552000 # Maximum price for items. This is important because the database providers integer/bigint values have a limit.

# The items that are not allowed to be listed in shop
banned_items:
  - BEDROCK
  - COMMAND_BLOCK

# Set each rank with a custom limit
# • max_listed_items (integer): The maximum items that the player can list in the shop
ranks:
  default:
    max_listed_items: 4
  vip:
    max_listed_items: 8
  moderator:
    max_listed_items: 12
  owner:
    max_listed_items: 100

# GUIs configuration
gui:
  __CONFIG_PAGINATION__:
    PREVIOUS_PAGE:
      displayname: "&9Previous"
      lore: null
      material: "PLAYERHEAD-86971dd881dbaf4fd6bcaa93614493c612f869641ed59d1c9363a3666a5fa6"

    CENTERED_INFO_ITEM:
      displayname: "&7Page &3%current_page%&7/&c%total_pages%"
      lore: null
      material: "PAPER"

    NEXT_PAGE:
      displayname: "&9Next"
      lore: null
      material: "PLAYERHEAD-f32ca66056b72863e98f7f32bd7d94c7a0d796af691c9ac3a9136331352288f9"

  shop:
    title: "&9Shop"
    contents:
      BUILDING_BLOCKS:
        displayname: "&2Building Blocks"
        lore:
          - ""
          - "&7Click to Open"
        material: GRASS_BLOCK

      TOOLS:
        displayname: "&fTools"
        lore:
          - ""
          - "&7Click to Open"
        material: IRON_PICKAXE

      FOOD:
        displayname: "&dFood"
        lore:
          - ""
          - "&7Click to Open"
        material: COOKED_BEEF
        
      MINERALS:
        displayname: "&bMinerals"
        lore:
          - ""
          - "&7Click to Open"
        material: DIAMOND

      NATURAL:
        displayname: "&aNatural"
        lore:
          - ""
          - "&7Click to Open"
        material: OAK_SAPLING

      REDSTONE:
        displayname: "&cRedstone"
        lore:
          - ""
          - "&7Click to Open"
        material: REDSTONE

      MISCELLANEOUS:
        displayname: "&6Miscellaneous"
        lore:
          - ""
          - "&7Click to Open"
        material: LAVA_BUCKET

      MY_PROFILE:
        enabled: true
        displayname: "&9My Profile"
        lore:
          - "&aPlayername: &f%player_name%"
          - "&aBalance: &f$%player_balance%"
        material: "PLAYERHEAD-72c170300a3add5dcbe32a21248b704b09b7feec975e4b39ca9358b65af12462"

      HELP:
        enabled: true
        displayname: "&7Help?"
        lore:
          - "&7• &9How to buy an item?"
          - "&7> &aSelect a category, search for a material you want"
          - "&ato buy, select the cheapest item, and then buy it!"
          - ""
          - "&7• &9How to sell an item?"
          - "&7> &aHold an item that you want to sell and use the"
          - "&afollowing command: &7/sell [price]"
          - "&aExamples: &7/sell 1200&a, &7/sell 1.2k"
          - ""
          - "&7• &9How do I get my items back?"
          - "&7> &aUse the following command: &7/listed"
        material: "PLAYERHEAD-89a995928090d842d4afdb2296ffe24f2e944272205ceba848ee4046e01f3168"

  shop_category:
    titles:
      BUILDING_BLOCKS: "&9Shop &8> &2Building Blocks"
      TOOLS: "&9Shop &8> &fTools"
      FOOD: "&9Shop &8> &dFood"
      MINERALS: "&9Shop &8> &bMinerals"
      NATURAL: "&9Shop &8> &aNatural"
      REDSTONE: "&9Shop &8> &cRedstone"
      MISCELLANEOUS: "&9Shop &8> &6Miscellaneous"
    contents:
      ITEM:
        lore:
          - ""
          - "&aItems: &b%items_count%"
          - ""
          - "&7Click to Open"

  shop_specific_material:
    title: "&9Shop &8> &r%item_rarity_color%%item_name%"
    contents:
      ITEM:
        lore:
          - ""
          - "&7• &aSeller: &f%seller_name%"
          - "&7• &aPrice: &f$%item_price%"
          - "&7• &aExpires in: &f%item_expires%"
          - ""
          - "&7Click to Buy"

  shop_buy:
    title: "&9Buy %item_amount%x %item_name%"
    contents:
      CANCEL:
        displayname: "&cCancel"
        lore:
          - ""
          - "&7Click to Cancel"
        material: RED_STAINED_GLASS_PANE

      ITEM:
        __IF_SHULKER_IS_EMPTY__:
          lore:
            - "&7(Empty Shulker Box)"
        lore:
          - ""
          - "&7• &aPrice: &f$%item_price%"

      BUY:
        displayname: "&aBuy"
        lore:
          - ""
          - "&7Click to Buy the item"
        material: LIME_STAINED_GLASS_PANE

  listed_items:
    title: "&9Listed & Expired Items"
    contents:
      ITEM:
        lore:
          - ""
          - "&7• &aExpires in: &f%item_expires%"
          - ""
          - "&7Click to Remove"

# Messages configuration
messages:
  commands:
    listed:
      no_items_listed: "&8[&9Shop&8] &cYou have no items listed in the shop."

    sell:
      no_item_in_hand: "&8[&9Shop&8] &cYou are not holding an item to sell!"
      item_is_banned: "&8[&9Shop&8] &cThis item is not allowed to be on shop!"
      no_price_provided: "&8[&9Shop&8] &cYou must provide the price of the item! &7/sell [price]"
      price_error: "&8[&9Shop&8] &cThe price of the item must be a positive integer and/or end with a valid suffix (k, M, B, T, or Q)."
      price_over_max: "&8[&9Shop&8] &cToo expensive! The maximum price is %max_price%."
      max_listed_items_reached: "&8[&9Shop&8] &cYou cannot sell more items! Upgrade to Premium to unlock more features."
      item_sold: "&8[&9Shop&8] &aThe item &b%item_amount%x %item_name% &ais now listed in the shop!"

    shop:
      invalid_category: "&8[&9Shop&8] &cInvalid shop category!"
  
  guis:
    buy:
      invalid_item: "&8[&9Shop&8] &cThe item does not exist! The seller has removed the item, or someone else purchased the item."
      item_expired: "&8[&9Shop&8] &cThe item is expired; you cannot buy it."
      inventory_full: "&8[&9Shop&8] &cYour inventory is full! Please leave at least one slot empty."
      player_is_item_seller: "&8[&9Shop&8] &cYou cannot buy the items that you are currently selling! Use &7/listed &cto remove the items."
      too_expensive: "&8[&9Shop&8] &cYou don't have enough money to buy this item! Your current balance: $%player_balance%"
    
    listed:
      inventory_full: "&8[&9Shop&8] &cYour inventory is full! Please leave at least one slot empty."
  
  notification:
    player_buy: "&8[&9Shop&8] &aYour &b%item_amount%x %item_name% &ahas been purchased by &b%buyer_name% &afor $%item_price%!"

  permission_error: "&cYou do not have the permission to run this command."